In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [24]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [25]:
df['petal width (cm)'].max()

2.5

In [26]:
df.shape

(150, 4)

In [27]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [28]:
y = iris.target

In [29]:
from sklearn.model_selection  import train_test_split

In [30]:
X_train, y_train, X_test, y_test = train_test_split(df,y,test_size = 0.2)

In [31]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [32]:
svm_model = SVC()
lr_model = LogisticRegression()
d_model = DecisionTreeClassifier()
rc_model = RandomForestClassifier()

In [33]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler

In [38]:
type(df.columns[0])

str

#### Feature Scaling

In [39]:
normal = MinMaxScaler()

for i in df.columns:
    normal.fit(df[[i]])
    df[[i]] = normal.transform(df[[i]])
#df[['sepal length (cm)']] = normal.transform(df[['sepal length (cm)']])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

### On Logistic Regression

In [41]:
cross_val_score(lr_model, df, iris.target)

array([0.83333333, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [42]:
np.mean([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

0.973333334

### On SVM

In [43]:
cross_val_score(svm_model, iris.data, iris.target)

array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])

In [44]:
np.mean([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

0.9666666679999999

### On Decision Tree

In [45]:
cross_val_score(d_model, iris.data, iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [46]:
np.mean([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

0.9666666679999999

### Random Forest

In [47]:
cross_val_score(rc_model, iris.data, iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [48]:
np.mean([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

0.9533333339999999